# Generated by Django 3.0.2 on 2020-01-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20200117_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
